### DISCUSSION TITLE
Running on not-Windows?

### DISCUSSION THREAD

**Discussion by jedieaston** [microsoft/winget-create#160] [Ideas]
Does anyone know what the significant blockers would be to running wingetcreate on Linux or macOS? 

The reason I ask is that I was looking into writing a [packaged GitHub Action](https://docs.github.com/en/actions/creating-actions/about-actions) to run `wingetcreate update`, and the two options are JavaScript (which although it has access to Node, it can't install any executables on the runner or lock itself to a single OS), or packaging the action in a Docker container, which only supports Docker on Linux. The Docker method would be the one we'd have to use.

Currently the biggest blockers I see seem to have to do with wingetcreate requiring access to Windows only .NET libraries, some (most?) of which aren't managed by the Windows Package Manager team. I'm somewhat of a novice in .NET and I've only worked in .NET Core on Linux, so I don't know how hard it is to port these. If they rely on system stuff in Windows existing (like I don't know if there's a great way of opening a MSI file on Linux to get the Product Code, as a simple example), then it probably is not feasible. But I think cross-platform support would definitely be worth looking into.

(Also, I haven't even tried running it in Wine yet. Maybe that works?) 

Thanks!

**Comment by denelon** [comment]
@jedieaston I've been circulating this with the team. We're looking at all the dependencies to see where work needs to be done. It looks like we need microsoft/msix-packaging#366. There are a couple of other libraries we're going to take a look at as well. We do get lots of feedback to support Linux for development.

**Comment by jedieaston** [comment]
A little update on this, `wingetcreate new` and `wingetcreate update` work fine using Wine:

```
easton@Spintax:~$ WINEDEBUG=-all wine ./wingetcreate-self-contained.exe update Google.Chrome -v 100.0.100.100 -u https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi https://dl.google
.com/dl/chrome/install/googlechromestandaloneenterprise.msi
dbus[27966]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Retrieving latest manifest for Google.Chrome
Downloading and parsing: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi...
Downloading and parsing: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi...
Generating a preview of your manifests...
Version manifest preview:
# Created using wingetcreate 1.0.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 100.0.100.100
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0


Installer manifest preview:
# Created using wingetcreate 1.0.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 100.0.100.100
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- chrome
Protocols:
- http
- https
FileExtensions:
- htm
- html
- url
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 179D213071F06A1C35CA7E900E5CC7A827F3D91972E20D23C7039F8AF02DC4EC
  ProductCode: '{B24F0A95-6C38-3CA4-AFC8-7BDD38B8C51D}'
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: D53ED5276DF7BD025B9D5B9CF8518417FEF3373D73EAE17855292019696F71AA
  ProductCode: '{FBD93D83-F534-3D5A-A588-C0537FFFE970}'
ManifestType: installer
ManifestVersion: 1.1.0


Default locale manifest preview:
# Created using wingetcreate 1.0.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 100.0.100.100
PackageLocale: en-US
Publisher: Google LLC
PublisherUrl: https://www.google.com
PublisherSupportUrl: https://support.google.com/?hl=en
PrivacyUrl: https://policies.google.com/privacy?hl=en&fg=1
Author: Google LLC
PackageName: Google Chrome
PackageUrl: https://www.google.com/chrome
License: Proprietary freeware, based on open source components
LicenseUrl: https://www.google.com/chrome/terms/
Copyright: c 2021 Google, Inc.
CopyrightUrl: https://www.google.com/chrome/terms/
ShortDescription: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Description: A fast, secure, and free web browser built for the modern web. Chrome syncs bookmarks across all your devices, fills out forms automatically, and so much more.
Moniker: chrome
Tags:
- browser
- chromium
- cross-platform
- google
- internet
- internet-browser
- web
- web-browser
ManifestType: defaultLocale
ManifestVersion: 1.1.0



Manifest saved to Z:\home\easton\manifests\g\Google\Chrome\100.0.100.100

Manifest validation succeeded: True

easton@Spintax:~$
```

I think packaging a Docker container much like https://github.com/amake/innosetup-docker would be a great idea, I may work on it next time I have a few hours.
