### DISCUSSION TITLE
Handling matching failures for single installer updates

### DISCUSSION THREAD

**Discussion by ryfu-msft** [microsoft/winget-create#183] [Q&A]
Hi everyone,

Several members of the community have had issues with "matching" failures when using Winget-Create to update their single installer manifests. 

For example, when entering the following command:
```
wingetcreate update Microsoft.WindowsSDK -u https://download.microsoft.com/download/9/7/9/97982c1d-d687-41be-9dd3-6d01e52ceb68/windowssdk/winsdksetup.exe
```

The output returns:
```
Multiple matches found for X86 Burn installer detected from the url: https://download.microsoft.com/download/9/7/9/97982c1d-d687-41be-9dd3-6d01e52ceb68/windowssdk/winsdksetup.exe
```

When comparing with the existing manifest, it shows the Windows SDK installer to be an **x86 EXE** installer. 

```
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/4/2/2/42245968-6A79-4DA7-A5FB-08C0AD0AE661/windowssdk/winsdksetup.exe
  InstallerType: exe
  InstallerSha256: 2E28117E82B4D02FE30D564B835ACE9976612609271265872F20F2256A9C506B
  InstallerSwitches:
    Silent: /q
    SilentWithProgress: /q
```

How should we handle this scenario? Some users have pointed out that updating a single installer should just "work" since there is nothing else to match to, but we also don't want to overwrite existing metadata if the installerTypes don't match (i.e. switches for exe installers).  We want the update command to support autonomously updating as many single-installer packages as possible, but we also don't want to overstep and cause issues by overwriting the manifest. What do people feel is the best solution?
