### ISSUE TITLE
Installer node matching failing unexpectedly in latest release

### ISSUE THREAD

**Issue by apetresc** [microsoft/winget-create#118]
# Brief description of your issue

Since the v0.3.0.3 release which changed a bunch of matching logic to fix things like #105 (thanks!), some of the more normal matchings seem to fail. Here is an example:

```powershell
PS C:\Users\apetresc\src\winget\winget-pkgs> wingetcreate.exe update qBittorrent.qBittorrent -v 4.3.6 -u "https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_x64_setup.exe/download" "https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_setup.exe/download" -o .\manifests\q\qBittorrent\qBittorrent\4.3.6
Retrieving latest manifest for qBittorrent.qBittorrent
Downloading and parsing: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_x64_setup.exe/download...

Downloading and parsing: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_setup.exe/download...

Each new installer URL must have a match to an existing installer node based on installer type and architecture.
The following installers failed to match an existing installer node:

X86 Nullsoft installer detected from the url: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_setup.exe/download
```
However, as described in more detail below, this should be a trivial match against the identical 4.3.5 installer in the existing manifest.

# Steps to reproduce

1. Run
```powershell
wingetcreate.exe update qBittorrent.qBittorrent -v 4.3.6 -u "https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_x64_setup.exe/download" "https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.6/qbittorrent_4.3.6_setup.exe/download" -o .\manifests\q\qBittorrent\qBittorrent\4.3.6
```

# Expected behavior

I'd expect this call to succeed since the two provided installers exactly match the existing 4.3.5 manifest:

```yaml
Installers:
  - Architecture: x64
    InstallerType: nullsoft
    InstallerUrl: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.5/qbittorrent_4.3.5_x64_setup.exe/download
    InstallerSha256: 724F12CA08716E3CB179A00DED6212DEAAC05394C52E6B3ED735DBEB73E080AB
#    ProductCode: 
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
  - Architecture: x86
    InstallerType: nullsoft
    InstallerUrl: https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.5/qbittorrent_4.3.5_setup.exe/download
    InstallerSha256: 4C77B9DC3E54E1F9A5AC2DAC9464BC971324D39474A7A44032AE714EF0FC41AA
#    ProductCode: 
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
```

# Actual behavior

Fails as described in the summary, apparently failing to match the x86 nullsoft installer even though it's a perfect match for the 4.3.5 installer.

# Environment

```none
Windows Manifest Creator v0.3.0.3
```
