### ISSUE TITLE
WingetCreate update command failing during Pull Request submission due to issue with permission

### ISSUE THREAD

**Issue by TechWatching** [microsoft/winget-create#130]
# Brief description of your issue

I use WingetCreate update command in a [GitHub Actions workflow](https://github.com/nushell/nushell/actions/workflows/winget-submission.yml)  that aims at generating the manifest and submitting the PR to the winget packages repository. The manifest generation works fine but the Pull Request submission fails with a permission error although the PAT was generated with the public_repo permission: `Octokit.ForbiddenException: Must have admin rights to Repository.`

# Steps to reproduce

- Create a PAT with the public_repo permission, set it in the secrets of a GitHub repository ([Nushell](https://github.com/nushell/nushell) in my case with a secret named `NUSHELL_PAT`)
- Use that secret with the wingetcreate update command in a github actions workflow 
My workflow is the following (triggered by a release):
```yaml
name: Submit Nushell package to Windows Package Manager Community Repository 

on:
  release:
    types: [published]

jobs:

  winget:
    name: Publish winget package
    runs-on: windows-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        run: |
          iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
          $github = Get-Content '${{ github.event_path }}' | ConvertFrom-Json
          $installerUrl = $github.release.assets | Where-Object -Property name -match 'windows.msi' | Select -ExpandProperty browser_download_url -First 1
          .\wingetcreate.exe update Nushell.Nushell -s -v $github.release.tag_name -u $installerUrl -t ${{ secrets.NUSHELL_PAT }}
```

# Expected behavior

Update command should work and the PR should be created like in the following screenshot
![image](https://user-images.githubusercontent.com/15186176/128511982-e3d59063-449f-4353-94c5-585f6ad49138.png)
(the same github action script worked on my fork of the main repository)

# Actual behavior

Pull Request submission is failing with the following error:
![image](https://user-images.githubusercontent.com/15186176/128512103-633db801-b768-4c90-870c-82e851f67fb2.png)

This raises the following questions:
- Is the public_repo permission not enough to make wingetcreate work ? => It would be weird as I succeeded making it work with this permission in another fork.
- Should the creator of the PAT be the owner of the original repo (Nushell in my case) ? I don't see why as the submission is mainly about forking winget-pkgs and submitting a PR if I understood correctly.

It seems to me that what is failing is the push of the autogenerated branch to the winget-pkgs fork. But I don't know what is the problem exactly.

# Environment

Latest version of winget create is used (latest version is downloaded each time the workflow is run): currently 0.2.0.29
