### ISSUE TITLE
Support Windows Package Manager v1.1 schema

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-create#139]
# Description of the new feature/enhancement

The tool should support the new v1.1 schema. It should also be able to update v1.0 manifests to v1.1.

**Comment by OfficialEsco** [comment]
This kinda needs to be prioritized if we update YamlCreate to 1.1.0.
Currently it removes Metadata, but keeps the "ManifestVersion: 1.1.0" and "$schema=" line
Example the new AnyDesk manifest

https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AnyDeskSoftwareGmbH/AnyDesk/ad%207.0.2/AnyDeskSoftwareGmbH.AnyDesk.installer.yaml
```
# Created with YamlCreate.ps1 v2.0.2 $debug=AUSU.7-2-0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk
PackageVersion: ad 7.0.2
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
  InstallerSha256: 307B2EC75D5A4DB865FFA253F482263F183E86E1BCF627CE65BB45CDFCB1C295
  ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
  UpgradeBehavior: uninstallPrevious
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
  - DisplayVersion: 7.0.2
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://download.anydesk.com/AnyDesk.exe
  InstallerSha256: B95DF71D6ED6EC96FA0EB51BB33B9C5503696DF2C04CE69AE89E3EDEFD91558F
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Upgrade: --remove-first
    Custom: --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
  UpgradeBehavior: install
  ElevationRequirement: elevationRequired
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk
  - DisplayVersion: ad 7.0.2
ManifestType: installer
ManifestVersion: 1.1.0
```
turns into
```
# Created using wingetcreate 0.4.3.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk
PackageVersion: ad 7.0.3
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.0.0
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
  InstallerSha256: 307B2EC75D5A4DB865FFA253F482263F183E86E1BCF627CE65BB45CDFCB1C295
  UpgradeBehavior: uninstallPrevious
  ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://download.anydesk.com/AnyDesk.exe
  InstallerSha256: B95DF71D6ED6EC96FA0EB51BB33B9C5503696DF2C04CE69AE89E3EDEFD91558F
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Upgrade: --remove-first
    Custom: --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.1.0
```
