### ISSUE TITLE
Incorrect hashes computed when installer file names are not unique

### ISSUE THREAD

**Issue by chausner** [microsoft/winget-create#249]
### Brief description of your issue

When multiple installer URLs are passed that use a common name, winget-create overwrites the downloaded file in the temp directory and subsequently computes the same hash for the different variants.

### Steps to reproduce

Run
```
wingetcreate update WillowSoftware.AnvilStudio -v 22.03.02 -u https://anvilstudio.com/x/asinstall.exe https://anvilstudio.com/x64/asinstall.exe
```

### Expected behavior

The generated manifest should contain the correct file hashes for the two installer variants.

### Actual behavior

The generated manifest contains the wrong file hash for the x86 variant:
```yaml
Installers:
- Architecture: x64
  InstallerType: exe
  InstallerUrl: https://anvilstudio.com/x64/asinstall.exe
  InstallerSha256: 02FC70CD7CCC165A1F9089F0EF29BD3BA2E1A0374D502A7E7784E7BA5C21AE46
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://anvilstudio.com/x/asinstall.exe
  InstallerSha256: 02FC70CD7CCC165A1F9089F0EF29BD3BA2E1A0374D502A7E7784E7BA5C21AE46
```

### Environment

```shell
Windows Manifest Creator v1.0.3.0
```
