### ISSUE TITLE
Allow updating a manifest with a different number of installer URLs

### ISSUE THREAD

**Issue by RuiNtD** [microsoft/winget-create#291]
### Description of the new feature / enhancement

Hello. I'm trying to update a package (`PolyMC.PolyMC`) that has stopped distributing 64-bit exes and I can't update the manifest because of this error:
> Updating a manifest is only supported with the same number of installer URLs.

This error should be a warning instead, prompting the user if they want to continue anyways.

**Comment by Trenly** [comment]
@FayneAldan - Just an FYI; PolyMC actually has a bot that submits their releases automatically https://github.com/microsoft/winget-pkgs/pull/67332

**Comment by FayneAldan** [comment]
Yes, I am aware. I tried to update the package manually after Winget Releaser picked the wrong installers, but Winget Create wouldn't let me do it.

**Comment by ryfu-msft** [comment]
Hey @FayneAldan, 

We actually do support your scenario. The reason why it didn't work is because the manifest of the latest version of PolyMC (v1.4) only has one installer URL which has already been checked in. We always use the latest version for the update. If that manifest wasn't checked in, you could have done something like this:

`wingetcreate update PolyMC.PolyMC --urls "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-x86_64-Setup-1.3.0.exe" "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-i686-Setup-1.3.0.exe"`

Winget-Create already has logic to help match the installers with the correct architecture but if you find that it didn't match it correctly, you can also override the detected architecture:

`wingetcreate update PolyMC.PolyMC --urls "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-x86_64-Setup-1.3.0.exe|x64" "https://github.com/PolyMC/PolyMC/releases/download/1.3.0/PolyMC-Windows-i686-Setup-1.3.0.exe|x86"`

Just fyi, in case you ever try this again in the future :)

**Comment by Jaifroid** [comment]
Well, I'm also getting this error but with manifests that have two entries for the SAME installer/architecture, due to scope `user` and scope `machine`. Latest version of winget-create errors out when trying to update manifest with these entries (only the installer entries shown here):

```
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
  InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/Kiwix-JS-Electron-Setup-2.0.9-E.exe
  InstallerSha256: AFE82A7B77ADFD259B336BB0DFE85D88098CDB43DCC6C307E35D1922233EA8E7
  InstallerSwitches:
    Custom: /ALLUSERS
```

This used to work, so it's a recent issue.
