### ISSUE TITLE
Submitting a manifest fails with `ERROR: Value cannot be null. (Parameter 'source')`

### ISSUE THREAD

**Issue by Cyberboss** [microsoft/winget-create#429]
### Brief description of your issue

Cannot submit packages using wingetcreate

### Steps to reproduce

```ps
wingetcreate submit -p "Tgstation.Server version 5.13.5" -t $Env:WINGET_PUSH_TOKEN .
```

Manifest files in `.`:
Tgstation.Server.installer.yaml:
```yml
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Tgstation.Server
PackageVersion: 5.13.5 # Do not change. Set before publish by push_manifest.ps1
Installers:
- InstallerUrl: https://github.com/tgstation/tgstation-server/releases/download/tgstation-server-v5.13.5/tgstation-server-installer.exe # Do not change. Set before publish by push_manifest.ps1
  InstallerLocale: en-US
  Architecture: x86
  InstallerType: burn
  Scope: machine
  InstallerSha256: AF9C71F6D08F5A1ED5F749A09E778F3E925C678721B94D1F23D71AD661CB2DBA # Do not change. Set before publish by push_manifest.ps1
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  ProductCode: '{D24887FA-3228-4509-B5F3-4E07E349F278}'
  UnsupportedOSArchitectures:
  - arm
  - arm64
  ElevationRequirement: elevatesSelf
  AppsAndFeaturesEntries:
  - DisplayName: tgstation-server
    DisplayVersion: 5.13.5 # Do not change. Set before publish by push_manifest.ps1
    Publisher: /tg/station 13
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.HostingBundle.6
  ReleaseDate: 2023-08-12 # Do not change. Set before publish by push_manifest.ps1
ManifestType: installer
ManifestVersion: 1.4.0
```

Tgstation.Server.locale.en-US.yaml:
```yml
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Tgstation.Server
PackageVersion: 5.13.5 # Do not change. Set before publish by push_manifest.ps1
PackageLocale: en-US
Publisher: /tg/station 13
PublisherUrl: https://github.com/tgstation/tgstation-server
PublisherSupportUrl: https://github.com/tgstation/tgstation-server/discussions/categories/q-a
Author: Dominion/Cyberboss
PackageName: tgstation-server
License: AGPL-3.0
ShortDescription: A production scale tool for BYOND server management
Moniker: tgstation-server
Documentations:
  - DocumentLabel: README.md
    DocumentUrl: https://github.com/tgstation/tgstation-server/blob/tgstation-server-v5.13.5/README.md # Do not change. Set before publish by push_manifest.ps1
ReleaseNotesUrl: https://github.com/tgstation/tgstation-server/releases/tag/tgstation-server-v5.13.5
PurchaseUrl: https://github.com/sponsors/Cyberboss
ManifestType: defaultLocale
ManifestVersion: 1.4.0
```

Tgstation.Server.yaml
```yml
# Created using wingetcreate 1.2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.4.0.schema.json

PackageIdentifier: Tgstation.Server
PackageVersion: 5.13.5 # Do not change. Set before publish by push_manifest.ps1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.4.0
```

### Expected behavior

Package submits successfully

### Actual behavior

```shell
PS S:\workspace\tgstation-server\build\package\winget\manifest> wingetcreate submit -p "Tgstation.Server version 5.13.5" -t $Env:WINGET_PUSH_TOKEN .
Manifest validation succeeded: True

Submitting pull request for manifest...

ERROR: Value cannot be null. (Parameter 'source')
```

### Environment

```shell
PS S:\workspace\tgstation-server\build\package\winget\manifest> wingetcreate --help
Windows Package Manager Manifest Creator v1.5.1.0

Copyright (c) Microsoft Corporation. All rights reserved.

The manifest creation command line utility generates manifest for submitting
apps to the Windows Package Manager repo.

  new         Launches a series of questions to help generate a new manifest
  update      Updates fields of an existing manifest
  submit      Submits a valid manifest directly to the Windows Package Manager repo
  settings    Open settings
  token       Modifies the GitHub auth token cache
  cache       Manage downloaded installers stored in cache

More help can be found at: https://aka.ms/winget-create
Privacy statement: https://aka.ms/privacy
```

```shell
PS S:\workspace\tgstation-server\build\package\winget\manifest> winget --info
Windows Package Manager (Preview) v1.6.1573-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3324
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
