### ISSUE TITLE
Add ProductCode input (maybe automatically)

### ISSUE THREAD

**Issue by tiziodcaio** [microsoft/winget-create#43]
# Description of the new feature/enhancement

In some MSIs, like chrome, it will be necessary to insert a "product code", otherwise winget will not recognise the updates.

# Proposed technical implementation details (optional)

 (I don't know how to get it for the winget-create, but manually you can get it from "winget list" when the app is already installed. If I find something, I will add down here

# Photos

![immagine](https://user-images.githubusercontent.com/61084118/120207045-38aacf80-c22c-11eb-9408-64b617c94b3c.png)

**Comment by OfficialEsco** [comment]
`wingetcreate new` actually does add the ProductCode, i believe it uses `Get-AppLockerFileInformation` which works most of the time, but not for everything.
`wingetcreate update` does however not fetch the ProductCode.

**Comment by tiziodcaio** [comment]
Woops sorry I'm not so expert... Sorry for saying fake things :/

**Comment by OfficialEsco** [comment]
You are still not wrong tho, i'm pretty sure it only does this for MSI's, i also thought it didn't add ProductCode's until i had to babysit `wingetcreate new` PR's the last 2 days because a bunch of people with A LOT less knowledge then you found out about it 😄

**Comment by palenshus** [comment]
> [microsoft/winget-pkgs#15518](https://github.com/microsoft/winget-pkgs/pull/15518) for example didn't pick up the ProductCode

This is strange, I couldn't repro. When I ran:

    wingetcreate new new https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourcetreeEnterpriseSetup_3.4.4.msi

It correctly parsed the ProductCode:

```
# Created using wingetcreate

PackageIdentifier: Atlassian.Sourcetree
PackageVersion: 3.4.4.0
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://product-downloads.atlassian.com/software/sourcetree/windows/ga/SourcetreeEnterpriseSetup_3.4.4.msi
  InstallerSha256: 758AAA6A48E1C195B0C0A234AD2CF1FEE6B720F4A6DE6320F060272BBED73180
  ProductCode: '{0A007AE6-6A0D-42DB-8CF5-6E6E178E923C}'
ManifestType: installer
ManifestVersion: 1.0.0
```

It's possible the user removed it manually. You are correct though that the Update command should update it as well
