### ISSUE TITLE
WingetCreate Crashes

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [microsoft/winget-create#466]
Hmmm, wingetcreate crashes.
[WingetCreateLog-2023-10-28-19-13.160.txt](https://github.com/microsoft/winget-create/files/13195677/WingetCreateLog-2023-10-28-19-13.160.txt)

**Comment by mdanish-kh** [comment]
What version of winget-create are you using? (it's shown in the output of running command `wingetcreate`)

I tried to run the command you are using in the logs and I can run them with no issues (both in autonomous and in interactive update) on the latest 1.5.5.0 client

```
 ~ wingetcreate update --urls "https://download.microsoft.com/download/b/8/5/b85bd06f-491c-4c1c-923e-75ce2fe2378e/windowssdk/winsdksetup.exe|x86" -v 10.0.22621.1778 Microsoft.WindowsSDK.10.0.22621
Retrieving latest manifest for Microsoft.WindowsSDK.10.0.22621
Overriding https://download.microsoft.com/download/b/8/5/b85bd06f-491c-4c1c-923e-75ce2fe2378e/windowssdk/winsdksetup.exe with architecture X86
Downloading and parsing: https://download.microsoft.com/download/b/8/5/b85bd06f-491c-4c1c-923e-75ce2fe2378e/windowssdk/winsdksetup.exe...
Generating a preview of your manifests...
Version manifest preview:
# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.10.0.22621
PackageVersion: 10.0.22621.1778
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0

Installer manifest preview:
# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.10.0.22621
PackageVersion: 10.0.22621.1778
MinimumOSVersion: 10.0.0.0
InstallerType: burn
InstallerSwitches:
  Silent: /q
  SilentWithProgress: /q
  Log: " "
UpgradeBehavior: uninstallPrevious
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/b/8/5/b85bd06f-491c-4c1c-923e-75ce2fe2378e/windowssdk/winsdksetup.exe
  InstallerSha256: 1BF94F7D2CF44CDF50124C3B5745A27B517367435F1BD5D0F127A33B2BD8344C
ManifestType: installer
ManifestVersion: 1.5.0

Default locale manifest preview:
# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Microsoft.WindowsSDK.10.0.22621
PackageVersion: 10.0.22621.1778
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://www.microsoft.com/en-us/
PublisherSupportUrl: https://support.microsoft.com/en-us
PrivacyUrl: https://privacy.microsoft.com/en-us/privacystatement
Author: Microsoft Corporation
PackageName: Windows Software Development Kit - Windows 10.0.22621.2428
License: Proprietary
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
ShortDescription: The Windows Software Development Kit (10.1.22621.2428) for Windows 11 provides the latest headers, libraries, metadata, and tools for building Windows apps.
ManifestType: defaultLocale
ManifestVersion: 1.5.0


Manifest saved to ***\manifests\m\Microsoft\WindowsSDK\10\0\22621\10.0.22621.1778

Manifest validation succeeded: True
```
