### ISSUE TITLE
`wingetcreate update` / `wingetcreate update -i` Installer version problem

### ISSUE THREAD

**Issue by ghost** [microsoft/winget-create#503]
### Brief description of your issue

wingetcreate fails to identify installer new version and replaces only hash in old version manifests.

### Steps to reproduce

`wingetcreate update WHONET.2023`
New version number is 23.13.8 but wingetcreate updated installer hash in old version 23.12.14 manifest.
![Screenshot (12)](https://github.com/microsoft/winget-create/assets/155899372/a40b6eb0-887e-4dbd-9c1b-d89c93a49da2)

### Expected behavior

It should detect new version number from installer and detect that package is using vanity url.
So it should replace old version with new version manifest.

### Actual behavior

```
PS C:\Users\drsht> wingetcreate update WHONET.2023
Retrieving latest manifest for WHONET.2023
Downloading and parsing: https://whonet.org/WHONET2023-Setup-x86.exe...
Downloading and parsing: https://whonet.org/WHONET2023-Setup-x64.exe...

The architecture detected from the binary might be different than what is specified in the installer URL for the following installer(s):
Using architecture detected from URL (X64), overriding architecture detected from binary (X86)
https://whonet.org/WHONET2023-Setup-x64.exe

Generating a preview of your manifests...
Version manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0

Installer manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
InstallerType: burn
Installers:
- Architecture: x86
  InstallerUrl: https://whonet.org/WHONET2023-Setup-x86.exe
  InstallerSha256: AA35364ABEE7B1229533E781173733AEE628D1293557C8688F4225F56958BCBA
- Architecture: x64
  InstallerUrl: https://whonet.org/WHONET2023-Setup-x64.exe
  InstallerSha256: 0B8C70A5B148C476A83A505C74D18EA9A7C7F34F3BAE108CBB9FC1725248A9F6
ManifestType: installer
ManifestVersion: 1.5.0

Default locale manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
PackageLocale: en-US
Publisher: Brigham and Women's Hospital
PublisherUrl: https://whonet.org
PublisherSupportUrl: https://whonet.org/contact.html
Author: Brigham and Women's Hospital
PackageName: WHONET 2023
PackageUrl: https://whonet.org/software.html
License: Freeware
Copyright: Copyright (c) Brigham and Women's Hospital. All rights reserved.
ShortDescription: WHONET is a free desktop Windows application for the management and analysis of microbiology laboratory data with a particular focus on antimicrobial resistance surveillance.
Description: |-
  WHONET is a free desktop Windows application for the management and analysis of microbiology laboratory data with a particular focus on antimicrobial resistance surveillance developed and supported by the WHO Collaborating Centre for Surveillance of Antimicrobial Resistance at the Brigham and Women's Hospital in Boston, Massachusetts.
  WHONET, available in 44 languages, supports local, national, regional, and global surveillance efforts in over 2,300 hospital, public health, animal health, and food laboratories in over 130 countries worldwide.
  WHONET 2023 is a modernized and expanded version of WHONET 5.6. This version supports 44 languages and includes new features for exporting to the WHO GLASS data structure.
  It includes support for CLSI 2023 M100, M45, M60, M61, as well as EUCAST 2023 bacterial breakpoints. Also included are the most recent CLSI VET01, VET03/04, and VET06 breakpoints.
Moniker: WHONET
Tags:
- Microbiology
- Laboratory
- Bacteriology
- BacLink
- AMR
- Antibiotics
- Resistance
- CLSI
- EUCAST
- WHO
- GLASS
ManifestType: defaultLocale
ManifestVersion: 1.5.0


Manifest saved to %USERPROFILE%\manifests\w\WHONET\2023\23.12.14

Manifest validation succeeded: True
```
`wingetcreate update WHONET.2023 -i`
```
Generating a preview of your manifests...
Version manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.5.0

Installer manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
InstallerType: burn
Installers:
- Architecture: x86
  InstallerUrl: https://whonet.org/WHONET2023-Setup-x86.exe
  InstallerSha256: AA35364ABEE7B1229533E781173733AEE628D1293557C8688F4225F56958BCBA
- Architecture: x64
  InstallerUrl: https://whonet.org/WHONET2023-Setup-x64.exe
  InstallerSha256: 0B8C70A5B148C476A83A505C74D18EA9A7C7F34F3BAE108CBB9FC1725248A9F6
ManifestType: installer
ManifestVersion: 1.5.0

Default locale manifest preview:
# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: WHONET.2023
PackageVersion: 23.12.14
PackageLocale: en-US
Publisher: Brigham and Women's Hospital
PublisherUrl: https://whonet.org
PublisherSupportUrl: https://whonet.org/contact.html
Author: Brigham and Women's Hospital
PackageName: WHONET 2023
PackageUrl: https://whonet.org/software.html
License: Freeware
Copyright: Copyright (c) Brigham and Women's Hospital. All rights reserved.
ShortDescription: WHONET is a free desktop Windows application for the management and analysis of microbiology laboratory data with a particular focus on antimicrobial resistance surveillance.
Description: |-
  WHONET is a free desktop Windows application for the management and analysis of microbiology laboratory data with a particular focus on antimicrobial resistance surveillance developed and supported by the WHO Collaborating Centre for Surveillance of Antimicrobial Resistance at the Brigham and Women's Hospital in Boston, Massachusetts.
  WHONET, available in 44 languages, supports local, national, regional, and global surveillance efforts in over 2,300 hospital, public health, animal health, and food laboratories in over 130 countries worldwide.
  WHONET 2023 is a modernized and expanded version of WHONET 5.6. This version supports 44 languages and includes new features for exporting to the WHO GLASS data structure.
  It includes support for CLSI 2023 M100, M45, M60, M61, as well as EUCAST 2023 bacterial breakpoints. Also included are the most recent CLSI VET01, VET03/04, and VET06 breakpoints.
Moniker: WHONET
Tags:
- Microbiology
- Laboratory
- Bacteriology
- BacLink
- AMR
- Antibiotics
- Resistance
- CLSI
- EUCAST
- WHO
- GLASS
ReleaseNotesUrl: https://whonet.org/WHONET-ReleaseNotes.html
ManifestType: defaultLocale
ManifestVersion: 1.5.0


Manifest saved to %USERPROFILE%\manifests\w\WHONET\2023\23.12.14

Manifest validation succeeded: True
```

![Screenshot (10)](https://github.com/microsoft/winget-create/assets/155899372/85a9c1e3-3837-479a-8d67-219984eefaaa)

### Environment

```shell
PS C:\Users\drsht> wingetcreate --help
Windows Package Manager Manifest Creator v1.5.7.0
```
```
PS C:\Users\drsht> winget --info
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
```
```
